version: 0.1.0.{build}
os: Visual Studio 2017
cache:
- C:\vcpkg
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  version: 17
  matrix:
    - TRIPLET: x86-windows-static-winssl
#    - TRIPLET: x64-windows-static-winssl
#    - TRIPLET: x86-uwp
#    - TRIPLET: x64-uwp
#    - TRIPLET: arm-uwp
#    - TRIPLET: arm-windows
#    - TRIPLET: arm64-windows
#    - TRIPLET: arm64-uwp
install:
- cmd: install.bat
build_script:
- cmd: >-
    build.bat

    package.bat
test: off
artifacts:
- path: '**\openloco*.zip'
  name: Zip simplified archive
- path: '**\vcpkg*.zip'
  name: Zip vcpkg archive
- path: '**\vcpkg*.nupkg'
  name: NuGet vcpkg archive
deploy:
  provider: GitHub
  artifact: '**\openloco-libs-v$(version)*.zip'
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
