version: 1.1.0.{build}
os: Visual Studio 2017
cache:
- C:\vcpkg
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  version: 1.1.0
  matrix:
    - TRIPLET: x86-windows
#    - TRIPLET: x64-windows
#    - TRIPLET: x86-uwp
#    - TRIPLET: x64-uwp
#    - TRIPLET: arm-uwp
#    - TRIPLET: arm-windows
#    - TRIPLET: arm64-windows
#    - TRIPLET: arm64-uwp
install:
- cmd: windows\install.bat
build_script:
- cmd: windows\build.bat
test: off
artifacts:
- path: '**\vcpkg*.zip'
  name: Zip vcpkg archive
- path: '**\*.nupkg'
  name: NuGet vcpkg archive
deploy:
  provider: GitHub
  auth_token:
    secure: 49K/y43epwh5Sb8uY1l/TbIFRPcEq6fraQaYGS0bgWQJfONznd6hCqPUCg7WSX16
  artifact: /.*\.nupkg/
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
