name: CI
on: [push, pull_request]
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    env:
      CONFIGURATION: Release
      TRIPLET: x86-windows
      VERSION: 1.3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build dependencies
        run: windows\install.bat
      - name: Build artifacts
        run: windows\build.bat
      - name: Upload vcpkg archive (Zip)
        uses: actions/upload-artifact@v2
        with:
          name: Zip vcpkg archive
          path: '**\vcpkg*.zip'
      - name: Upload vcpkg archive (NuGet)
        uses: actions/upload-artifact@v2
        with:
          name: NuGet vcpkg archive
          path: '**\*.nupkg'
