name: CI
on: [push, pull_request, workflow_dispatch]
env:
  VCPKG_DISABLE_METRICS: 1
  VERSION: 1.5.0
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        VCPKG_DEFAULT_TRIPLET: [x86-windows]
    env:
      CONFIGURATION: Release
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.VCPKG_DEFAULT_TRIPLET }}
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build dependencies
        run: windows\install
      - name: Build artifacts
        run: windows\build
      - name: Upload vcpkg archive (zip)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.VCPKG_DEFAULT_TRIPLET }} vcpkg archive (zip)
          path: '.\vcpkg\vcpkg*.zip'
          if-no-files-found: error
      - name: Upload vcpkg archive (NuGet)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.VCPKG_DEFAULT_TRIPLET }} vcpkg archive (NuGet)
          path: '.\vcpkg\*.nupkg'
          if-no-files-found: error
#  macos:
#    name: macOS
#    runs-on: macos-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        VCPKG_DEFAULT_TRIPLET: [x86-osx]
#    env:
#      CONFIGURATION: Release
#      VCPKG_DEFAULT_TRIPLET: ${{ matrix.VCPKG_DEFAULT_TRIPLET }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: Build dependencies
#        run: macos/build.sh
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: ${{ matrix.VCPKG_DEFAULT_TRIPLET }} vcpkg archive (zip)
#          path: macos.dependencies.zip
#          if-no-files-found: error
